/*

                                    ,▄█▄                 
    ]█▄▄                         ╓█████▌                 
    ▐██████▄                   ▄█████▓╣█                 
     ║████████▄,  ,  ,,▄,▄▄▄▓██████╬╬╣╣▌                 
      ╚███╣██████████▓▓▓▓██████████╩╠╬▓                  
       ╙█╬╬╬▓███████████████████████▒▓▌                  
        ╙▓█▓██████████████████████████                   
         ╚██████▀███████████╩█▓▌▐▓████▄                  
         '║█████`╣█Γ║████████▄▄φ▓█████▌                 
          ║█████████████████████▓█████▌                  
           █████████████▓▓████████████                   
           ║█████████████████████████                    
          ]█████████████████████████                     
         ,▓██████████████████████████                    
        ▓█████████████████████████████µ                  
       ▐███████████████████████████████▄▄                
       ║█████████████████████████████████╬╬╣▓            
   ,╔╦║███████████████████████████████████▓╬╬╣           
,≥≥⌠░░░╠▓████████████████████████████████████▓▓          
,;=-',▄█████████████████████████████████████████▓        
                                                         
                                                         
                                                         
  ██████╗ ███████╗██╗   ██╗ ██████╗██╗  ██╗██╗ ██████╗   
  ██╔══██╗██╔════╝╚██╗ ██╔╝██╔════╝██║  ██║██║██╔════╝   
  ██████╔╝███████╗ ╚████╔╝ ██║     ███████║██║██║        
  ██╔═══╝ ╚════██║  ╚██╔╝  ██║     ██╔══██║██║██║        
  ██║     ███████║   ██║   ╚██████╗██║  ██║██║╚██████╗   
  ╚═╝     ╚══════╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚═╝ ╚═════╝   
                                                         
                                                         

This file was automatically generated by my cat, Aster.
He does not want you mucking about with his files,
and we are pretty lax on trimming his nails.

I mean, we have him pretty well fenced in but he is an
escape artist and he still manages to get fleas!

My point is, don't go mucking about with his files!

He actually has a hopefully well-tempered message for
us humans, he says:

"
  Dear pathetic humans,

  Here is a haiku to keep you in line

  don't dare go mucking
  with my files, I lyke them fine
  prettierignore
"

*/

import {
  type CalendarDate,
  type DateTime,
  type ClockTime,
  type ClockTimeTz,
} from '@rvoh/dream'
import {} from './db.js'

export const schema = {
  comments: {
    serializerKeys: [],
    scopes: {
      default: [],
      named: [],
    },
    nonJsonColumnNames: [
      'body',
      'createdAt',
      'id',
      'numLikes',
      'postId',
      'updatedAt',
      'userId',
    ],
    columns: {
      body: {
        coercedType: {} as string | null,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: true,
        isArray: false,
      },
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as string,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      numLikes: {
        coercedType: {} as number | null,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: true,
        isArray: false,
      },
      postId: {
        coercedType: {} as string,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      userId: {
        coercedType: {} as string,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      post: {
        type: 'BelongsTo',
        foreignKey: 'postId',
        foreignKeyTypeColumn: null,
        tables: ['posts'],
        optional: false,
        requiredAndClauses: null,
        passthroughAndClauses: null,
      },
      user: {
        type: 'BelongsTo',
        foreignKey: 'userId',
        foreignKeyTypeColumn: null,
        tables: ['users'],
        optional: false,
        requiredAndClauses: null,
        passthroughAndClauses: null,
      },
    },
  },
  posts: {
    serializerKeys: [],
    scopes: {
      default: ['dream:SoftDelete'],
      named: [],
    },
    nonJsonColumnNames: [
      'body',
      'createdAt',
      'deletedAt',
      'id',
      'subtitle',
      'title',
      'updatedAt',
      'userId',
    ],
    columns: {
      body: {
        coercedType: {} as string | null,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: true,
        isArray: false,
      },
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      deletedAt: {
        coercedType: {} as DateTime | null,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: true,
        isArray: false,
      },
      id: {
        coercedType: {} as string,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      subtitle: {
        coercedType: {} as string | null,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: true,
        isArray: false,
      },
      title: {
        coercedType: {} as string | null,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: true,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      userId: {
        coercedType: {} as string,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      comments: {
        type: 'HasMany',
        foreignKey: 'postId',
        foreignKeyTypeColumn: null,
        tables: ['comments'],
        optional: null,
        requiredAndClauses: null,
        passthroughAndClauses: null,
      },
      mostRecentComment: {
        type: 'HasOne',
        foreignKey: 'postId',
        foreignKeyTypeColumn: null,
        tables: ['comments'],
        optional: null,
        requiredAndClauses: null,
        passthroughAndClauses: null,
      },
      mostRecentNullComment: {
        type: 'HasOne',
        foreignKey: 'postId',
        foreignKeyTypeColumn: null,
        tables: ['comments'],
        optional: null,
        requiredAndClauses: null,
        passthroughAndClauses: null,
      },
      nullComments: {
        type: 'HasMany',
        foreignKey: 'postId',
        foreignKeyTypeColumn: null,
        tables: ['comments'],
        optional: null,
        requiredAndClauses: null,
        passthroughAndClauses: null,
      },
      user: {
        type: 'BelongsTo',
        foreignKey: 'userId',
        foreignKeyTypeColumn: null,
        tables: ['users'],
        optional: false,
        requiredAndClauses: null,
        passthroughAndClauses: null,
      },
    },
  },
  tree_nodes: {
    serializerKeys: [],
    scopes: {
      default: [],
      named: [],
    },
    nonJsonColumnNames: ['createdAt', 'id', 'name', 'treeNodeId', 'updatedAt'],
    columns: {
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      id: {
        coercedType: {} as string,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      name: {
        coercedType: {} as string,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: false,
        isArray: false,
      },
      treeNodeId: {
        coercedType: {} as string | null,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: true,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      children: {
        type: 'HasMany',
        foreignKey: 'treeNodeId',
        foreignKeyTypeColumn: null,
        tables: ['tree_nodes'],
        optional: null,
        requiredAndClauses: null,
        passthroughAndClauses: null,
      },
      parent: {
        type: 'BelongsTo',
        foreignKey: 'treeNodeId',
        foreignKeyTypeColumn: null,
        tables: ['tree_nodes'],
        optional: true,
        requiredAndClauses: null,
        passthroughAndClauses: null,
      },
    },
  },
  users: {
    serializerKeys: [],
    scopes: {
      default: [],
      named: [],
    },
    nonJsonColumnNames: [
      'createdAt',
      'email',
      'id',
      'loginCount',
      'name',
      'updatedAt',
    ],
    columns: {
      createdAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
      email: {
        coercedType: {} as string | null,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: true,
        isArray: false,
      },
      id: {
        coercedType: {} as string,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'bigint',
        allowNull: false,
        isArray: false,
      },
      loginCount: {
        coercedType: {} as number | null,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'integer',
        allowNull: true,
        isArray: false,
      },
      name: {
        coercedType: {} as string | null,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'character varying',
        allowNull: true,
        isArray: false,
      },
      updatedAt: {
        coercedType: {} as DateTime,
        enumType: null,
        enumArrayType: null,
        enumValues: null,
        dbType: 'timestamp without time zone',
        allowNull: false,
        isArray: false,
      },
    },
    virtualColumns: [],
    associations: {
      comments: {
        type: 'HasMany',
        foreignKey: null,
        foreignKeyTypeColumn: null,
        tables: ['comments'],
        optional: null,
        requiredAndClauses: null,
        passthroughAndClauses: null,
      },
      commentsFollowingThrough: {
        type: 'HasMany',
        foreignKey: null,
        foreignKeyTypeColumn: null,
        tables: ['comments'],
        optional: null,
        requiredAndClauses: null,
        passthroughAndClauses: null,
      },
      mostRecentPost: {
        type: 'HasOne',
        foreignKey: 'userId',
        foreignKeyTypeColumn: null,
        tables: ['posts'],
        optional: null,
        requiredAndClauses: null,
        passthroughAndClauses: null,
      },
      posts: {
        type: 'HasMany',
        foreignKey: 'userId',
        foreignKeyTypeColumn: null,
        tables: ['posts'],
        optional: null,
        requiredAndClauses: null,
        passthroughAndClauses: null,
      },
      postsWithPassthroughOnClause: {
        type: 'HasMany',
        foreignKey: 'userId',
        foreignKeyTypeColumn: null,
        tables: ['posts'],
        optional: null,
        requiredAndClauses: null,
        passthroughAndClauses: ['title'],
      },
      postsWithRequiredOnClause: {
        type: 'HasMany',
        foreignKey: 'userId',
        foreignKeyTypeColumn: null,
        tables: ['posts'],
        optional: null,
        requiredAndClauses: ['title'],
        passthroughAndClauses: null,
      },
    },
  },
} as const

export const connectionTypeConfig = {
  passthroughColumns: ['title'],
  allDefaultScopeNames: ['dream:SoftDelete'],
  globalNames: {
    models: {
      Comment: 'comments',
      Post: 'posts',
      TreeNode: 'tree_nodes',
      User: 'users',
    },
  },
} as const
